# config.yaml
schedule:
  send_days_before: 3
  menu_duration_days: 14
  send_time: "09:00"  # When to send on scheduled day

paths:
  output: "output"  # Where to save generated menus
  logs: "logs"      # Where to save log files
  templates: "menu_templates"  # Directory for menu templates

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  imap_server: "imap.gmail.com"
  sender_email: "" # Will be overridden by environment variable
  password: "" # Will be overridden by environment variable

processing:
  poppler_path: "C:\\Poppler\\Release-24.08.0-0\\poppler-24.08.0\\Library\\bin"
  tesseract_path: "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"