# config.yaml
schedule:
  send_days_before: 3
  menu_duration_days: 14
  send_time: "09:00"  # When to send on scheduled day

paths:
  temp_dir: "temp_images"  # Where to save temporary files
  output_dir: "output_images"  # Where to save generated menus
  logs_dir: "logs"      # Where to save log files
  templates_dir: "menu_templates"  # Directory for menu templates

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  imap_server: "imap.gmail.com"
  sender_name: "Holly Lodge Menu System"
  sender_email: "" # Will be overridden by environment variable
  password: "" # Will be overridden by environment variable

processing:
  poppler_path: "/usr/bin"  # Linux system path for Poppler
  tesseract_path: "/usr/bin/tesseract"  # Linux system path for Tesseract

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Directory paths
temp_dir: "temp_images"
output_dir: "output_images"
templates_dir: "menu_templates"
logs_dir: "logs"